### ISSUE TITLE
[idea] extend SLINK interrupts

### ISSUE THREAD

**Issue by stnolting** [stnolting/neorv32#376]
This idea was started by @betocool-prog in the NEORV32 [gitter channel](https://gitter.im/neorv32/community):

> If it's size configurable and channel configurable, yes. But we'd need to add an additional status register, maybe, to read out which interrupt it was. I'm thinking:
>    At least one data word => transition from empty to non empty
>    Half or more full => from (size/2 - 1) to size/2
>    Full => No space available... equivalent to overflow?
>    Empty => transition from at least one to 0 elements.
>  My strategy as C programmer would be to read Size/2 samples every time I get a half-full interrupt, or if not using interrupt, reading the half-full status bit(s).

The SLINK module provides **just** two interrupt lines: one for signaling TX-related events and another one for signaling RX-related events. I agree that a more fine-grained interrupt cause configuration is a good idea (especially the half-full situation).

Do we need all four interrupt options for RX and TX? From my (limited) understanding two conditions per RX/TX might be sufficient:

**RX**
* FIFO gets not empty (data received/available)
* FIFO gets at least half full (time to read data block)

**TX**
* FIFO gets empty
* FIFO gets less than half full (time to send new data block)

The thing with an RX overflow is interesting. Do you think an explicit interrupt conditions is required for this? Maybe we could add a simple 1-bit flag for each RX channel to check for overruns?!

**Comment by betocool-prog** [comment]
It's possible to set one interrupt for the RX line and one interrupt for the TX line for the CPU and still get the full feature of events by OR'ing the flags internally inside the SLINK module.

The RX/TX interrupt signals only once, whenever any of the above conditions happen. Each condition is a flag on a interrupt status register, and as part of the ISR, the programmer should act accordingly. In some weird cases, it's possible that all interrupt flags are on, for example, if the buffer is never read. That also gives the programmer the possibility of ignoring certain interrupts.

The interrupts should/could be cleared by writing to the flag itself or by writing to an interrupt clear register. The first option I think is a bit more complicated to write, the second uses a few more resources.

**Comment by stnolting** [comment]
The NEORV32 internal interrupt are a bit "odd" I think... Whenever a certain interrupt condition is met, the according interrupt signal fires (1 cycle high). Then the interrupt becomes pending inside the CPU. The according interrupt handler then has to clear this "pending interrupt flag" in the CPU so it can trigger again.

Back to the SLINK. How about this: per-channel interrupt configuration plus a status register to check the FIFO level of each channel.

The modified SLINK register map would look something like this:
```
CTRL:
- enable/reset[1]      (r/w)
- rx_log2_fifo_size[4] (r/-)
- tx_log2_fifo_size[4] (r/-)

IRQ:
- rx_irq_mode[16] (r/w, 2-bit for each RX channel)
  - 00: off
  - 01: off (unused)
  - 10: trigger IRQ when FIFO(i) goes from "empty" to "not empty"
  - 11: trigger IRQ when FIFO(i) becomes "at least half full"
- tx_irq_mode[16] (r/w, 2-bit for each RX channel)
  - 00: off
  - 01: off (unused)
  - 10: trigger IRQ when FIFO(i) goes from "not empty" to "empty"
  - 11: trigger IRQ when FIFO(i) becomes "at least half full"

RX_STATUS:
- rx_empty[8] (r/-)
- rx_half[8]  (r/-)
- rx_full[8]  (r/-)
- rx_last[8]  (r/-)

TX_STATUS:
- tx_empty[8] (r/-)
- tx_half[8]  (r/-)
- tx_full[8]  (r/-)
- tx_last[8]  (r/w)

DATA[8]:
- LINK[8][32] (r/w)
```

**Comment by betocool-prog** [comment]
I don't think the NEORV32 is odd in that sense, I've seen lots of other cases where you need to explicitly clear an interrupt before you can trigger it again.

What if instead of 16 IRQs (8 RX  + 8 TX) it's 2 IRQs total for SLINK with:
```
CTRL:
- enable/reset[1]      (r/w)
- rx_log2_fifo_size[4] (r/-)
- tx_log2_fifo_size[4] (r/-)

IRQ:
- rx_irq_mode[1] (r/w, 2-bit for each RX channel)
  - Channel[0..7] 
    - 00: off
    - 01: off (unused)
    - 10: trigger IRQ when FIFO(i) goes from "empty" to "not empty"
    - 11: trigger IRQ when FIFO(i) becomes "at least half full"
- tx_irq_mode[1] (r/w, 2-bit for each RX channel)
  Channel[0..7]  
    - 00: off
    - 01: off (unused)
    - 10: trigger IRQ when FIFO(i) goes from "not empty" to "empty"
    - 11: trigger IRQ when FIFO(i) becomes "at least half full"

RX_STATUS:
- rx_empty[8] (r/-)
- rx_half[8]  (r/-)
- rx_full[8]  (r/-)
- rx_last[8]  (r/-)

TX_STATUS:
- tx_empty[8] (r/-)
- tx_half[8]  (r/-)
- tx_full[8]  (r/-)
- tx_last[8]  (r/w)

DATA[8]:
- LINK[8][32] (r/w)
```
This would decrease the number of IRQ lines to the CPU, but then the programmer needs to handle them.

I haven't looked at the SLINK module in detail yet, so I don't know how complex the changes would be.
